language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - ENVIRONMENT=testing
  - CACHE_DIR=$HOME/wpf

cache:
  directories:
  - $HOME/wpf

before_install:
  - pip install --user codecov

install:
  - composer install

after_success:
  - codecov

notifications:
  email:
    - contacto@davidmartinez.net